# Generated by Django 4.2.1 on 2023-05-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=3, unique=True)),
                ('artist', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
            ],
        ),
    ]
