# Generated by Django 4.2.1 on 2023-05-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc_ranking', '0002_player_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='county',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
